### ISSUE TITLE
purge-kernels.service might conflict with other background services using zypper as well

### ISSUE THREAD

**Issue by Martchus** [openSUSE/mkinitrd#43]
I observed the following problem on a Leap 15.2 system (used as openQA worker):

```
martchus@openqaworker3:/srv/salt> sudo systemctl status purge-kernels.service
purge-kernels.service - Purge old kernels
   Loaded: loaded (/usr/lib/systemd/system/purge-kernels.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-03-15 06:51:54 CET; 1 day 4h ago
 Main PID: 1166 (code=exited, status=7)

Mar 15 06:51:36 openqaworker3 systemd[1]: Starting Purge old kernels...
Mar 15 06:51:54 openqaworker3 zypper[1166]: System management is locked by the application with pid 1286 (zypper).
Mar 15 06:51:54 openqaworker3 zypper[1166]: Close this application before trying again.
Mar 15 06:51:54 openqaworker3 systemd[1]: purge-kernels.service: Main process exited, code=exited, status=7/NOTRUNNING
Mar 15 06:51:54 openqaworker3 systemd[1]: Failed to start Purge old kernels.
Mar 15 06:51:54 openqaworker3 systemd[1]: purge-kernels.service: Unit entered failed state.
Mar 15 06:51:54 openqaworker3 systemd[1]: purge-kernels.service: Failed with result 'exit-code'.
```

Maybe this can be improved, e.g. by adding a retry?

**Comment by mwilck** [comment]
Why have you posted this in the mkinitrd repo? This has nothing to do with mkintird. Also, does this happen during boot? If yes, why is zypper already running with PID 1286?

**Comment by Martchus** [comment]
Because it looks like the service file is provided by this repository: https://github.com/openSUSE/mkinitrd/blob/master/etc/purge-kernels.service

I'm not sure whether it happened during boot. Since I only saw this problem later when notified by the monitoring I can not tell what process corresponded to the PID at the time the service was executed. It was not running anymore.

**Comment by mwilck** [comment]
> Because it looks like the service file is provided by this repository: https://github.com/openSUSE/mkinitrd/blob/master/etc/purge-kernels.service

Please open a bug in bugzilla. `mkinitrd` is a legacy SLE11 package.
